### ISSUE TITLE
Checkbox

### ISSUE THREAD

**Issue by carolin913** [TDesignOteam/tdesign-web-components#10]
基于[OMI框架](https://omi.cdn-go.cn/home/latest/zh/introduction.html)完成t-checkbox和t-checkbox-group组件开发，要求完成以下功能即可：

### t-checkbox：
1、【props】：className, checked, disabled, indeterminate, readonly, value, label
2、【event】：onChange

### t-checkbox-group：
1、【props】：className, disabled,  value, max, options
2、【event】：onChange

以上api功能细则、ui样式、对应demo示例均参考已有[TDesign react/vue版](https://tdesign.tencent.com/react/components/checkbox)

**Comment by 1379255913** [comment]
认领
